# Generated by Django 2.2.1 on 2019-05-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190516_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadraManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeResultManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeShortManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_1', models.BooleanField(default=False)),
                ('_2', models.BooleanField(default=False)),
                ('_3', models.BooleanField(default=False)),
                ('_4', models.BooleanField(default=False)),
                ('_5', models.BooleanField(default=False)),
                ('_6', models.BooleanField(default=False)),
                ('_7', models.BooleanField(default=False)),
                ('_8', models.BooleanField(default=False)),
                ('_9', models.BooleanField(default=False)),
                ('_10', models.BooleanField(default=False)),
                ('_11', models.BooleanField(default=False)),
                ('_12', models.BooleanField(default=False)),
                ('_13', models.BooleanField(default=False)),
                ('_14', models.BooleanField(default=False)),
                ('_15', models.BooleanField(default=False)),
                ('_16', models.BooleanField(default=False)),
                ('_17', models.BooleanField(default=False)),
                ('_18', models.BooleanField(default=False)),
                ('_19', models.BooleanField(default=False)),
                ('_20', models.BooleanField(default=False)),
                ('_21', models.BooleanField(default=False)),
                ('_22', models.BooleanField(default=False)),
                ('_23', models.BooleanField(default=False)),
                ('_24', models.BooleanField(default=False)),
                ('_25', models.BooleanField(default=False)),
                ('_26', models.BooleanField(default=False)),
                ('_27', models.BooleanField(default=False)),
                ('_28', models.BooleanField(default=False)),
                ('test_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTestManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
