# Generated by Django 2.2.1 on 2019-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_quadramanager_typeresultmanager_typeshortmanager_typetest_typetestmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeTest',
        ),
    ]
